name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI Pipeline
        run: |
          curl -X POST \
          -F token=$GITLAB_TOKEN \
          -F ref=main \
          https://gitlab.com/api/v4/projects/76319499/trigger/pipeline
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
